//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Smerdova_PPEntities : DbContext
    {
        public Smerdova_PPEntities()
            : base("name=Smerdova_PPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiplomaTable> DiplomaTable { get; set; }
        public virtual DbSet<EmployeeTable> EmployeeTable { get; set; }
        public virtual DbSet<LoginedTable> LoginedTable { get; set; }
        public virtual DbSet<PassportTable> PassportTable { get; set; }
        public virtual DbSet<SickLeaveTable> SickLeaveTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
