//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDK
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
    
        public virtual LoginedTable LoginedTable { get; set; }
    }
}
